# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 22.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-7
    ports:
      - "8080:8000"
      - "8443:8443"
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=webshop.scot5.net
      - VIRTUAL_PORT=8000
      - CERT_NAME=scot5_net
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:7.2-fpm-0
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.2-fpm-0
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  sockdata:
